Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 40
  
Documentation:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/schema.rb
